In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = sns.load_dataset('iris')

In [10]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = df.drop('species',axis=1)
y = df['species']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### **KNN**

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
# model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn = KNeighborsClassifier(n_neighbors=13)

In [25]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.score(X_test,y_test)
# n = 5 >>>> A = 98%
# n = 13 >>>> A = 100% ----> Overfitted ----> This is prevented through Cross Validation

1.0

### **SVM**

In [27]:
from sklearn.svm import SVC

In [35]:
# model_svm = SVC(C=30,kernel='rbf',gamma='auto') 
# model_svm = SVC(C=10,kernel='linear',gamma='auto') 
model_svm = SVC(gamma='auto') # ----> For GridSearch CV

In [36]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [37]:
model_svm.score(X_test,y_test)

1.0

# **Grid Search CV**

### **SVM**

In [34]:
from sklearn.model_selection import GridSearchCV

In [38]:
classifier = GridSearchCV(model_svm,{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'] 
},cv=5,return_train_score=False)

In [39]:
classifier.fit(X,y) # We have not used X_train & y_train because CV will perform train-test-split by itself

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [40]:
classifier.cv_results_

{'mean_fit_time': array([0.00159106, 0.00163341, 0.00176301, 0.00292363, 0.00211086,
        0.00125813, 0.00502343, 0.00212727]),
 'std_fit_time': array([0.00029942, 0.00025721, 0.00056207, 0.00134004, 0.00038542,
        0.00014275, 0.00205805, 0.00014246]),
 'mean_score_time': array([0.00122833, 0.00141988, 0.00119028, 0.00226388, 0.00150752,
        0.00122008, 0.0040195 , 0.00143266]),
 'std_score_time': array([2.09313427e-04, 4.82310629e-04, 3.07382029e-04, 1.36759358e-03,
        3.91238190e-04, 5.78423120e-04, 4.33822322e-04, 7.87204571e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [41]:
results = pd.DataFrame(data=classifier.cv_results_)

In [42]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001591,0.000299,0.001228,0.000209,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001633,0.000257,0.001420,0.000482,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001763,0.000562,0.001190,0.000307,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002924,0.001340,0.002264,0.001368,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002111,0.000385,0.001508,0.000391,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001258,0.000143,0.001220,0.000578,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.005023,0.002058,0.004019,0.000434,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002127,0.000142,0.001433,0.000079,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [43]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

#### **Perform GridSearchCV for KNN**

# **Random Search CV**

In [44]:
from sklearn.model_selection import RandomizedSearchCV

In [46]:
classifier_r = RandomizedSearchCV(model_svm,{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'] 
},n_iter = 4,cv=5,return_train_score=False) # ----> 4 iterations

In [47]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results = pd.DataFrame(classifier_r.cv_results_)

In [49]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1       20       linear         0.966667
2       30       linear         0.960000
3       30          rbf         0.960000